# Generated by Django 4.0.10 on 2024-09-27 20:27

from django.db import migrations, models
import django.db.models.deletion
from wagtail.images import get_image_model_string


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailseo", "0003_seosettings_struct_org_fields"),
        migrations.swappable_dependency(get_image_model_string()),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="og_image_default",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. This can also be customized on each page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=get_image_model_string(),
                verbose_name="Default preview image",
            ),
        ),
    ]
