# Generated by Django 3.1.5 on 2021-01-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailseo', '0004_auto_20210121_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Apply this logo on all pages. It can be overwritten if another logo is uploaded on a specific page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization logo'),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='org_image',
            field=models.ForeignKey(blank=True, help_text='A photo of the facility. This photo will be cropped to 1:1, 4:3, and 16:9 aspect ratios automatically. Apply this logo on all pages. It can be overwritten if another logo is uploaded on a specific page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo of Organization'),
        ),
    ]
