# Generated by Django 3.2.10 on 2021-12-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailseo', '0002_remove_seosettings_amp_pages'),
        ('wagtailseo', '0005_auto_20210125_1602'),
    ]

    operations = [
    ]
