# Generated by Django 3.2.10 on 2021-12-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailseo', '0003_auto_20211227_1308'),
        ('wagtailseo', '0006_merge_20211227_0927'),
    ]

    operations = [
    ]
