# Generated by Django 3.2.5 on 2021-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='struct_org_geo_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Geographic latitude'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='struct_org_geo_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Geographic longitude'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='struct_org_geo_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Geographic latitude'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='struct_org_geo_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Geographic longitude'),
        ),
    ]
