# Generated by Django 3.2.10 on 2021-12-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0002_auto_20210731_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='breadcrumbs_are_active',
            field=models.BooleanField(default=True, help_text='If enabled, the breadcrumb object will be added as: https://example.org/{slug}/#breadcrumb . Also BreadCrumbList object will be added with the parent pages.', verbose_name='Breadcrumbs are active'),
        ),
        migrations.AddField(
            model_name='seopage',
            name='breadcrumbs_are_active',
            field=models.BooleanField(default=True, help_text='If enabled, the breadcrumb object will be added as: https://example.org/{slug}/#breadcrumb . Also BreadCrumbList object will be added with the parent pages.', verbose_name='Breadcrumbs are active'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='struct_org_logo',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use the logo in Settings > SEO > Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization logo'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='struct_org_logo',
            field=models.ForeignKey(blank=True, help_text='Leave blank to use the logo in Settings > SEO > Logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization logo'),
        ),
    ]
