# Generated by Django 4.0.10 on 2024-06-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_alter_articlepage_struct_org_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='struct_org_logo',
            field=models.ForeignKey(blank=True,
                                    help_text='Logo representative of the organisation. Must be 112x112px minimum; take note that it will be displayed on a white background',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.image', verbose_name='Organization logo'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='struct_org_logo',
            field=models.ForeignKey(blank=True,
                                    help_text='Logo representative of the organisation. Must be 112x112px minimum; take note that it will be displayed on a white background',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.image', verbose_name='Organization logo'),
        ),
    ]
