# Generated by Django 4.0.10 on 2024-06-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articlepage_struct_org_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_actions',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_address_country',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_address_locality',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_address_postal',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_address_region',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_address_street',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_extra_json',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_geo_lat',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_geo_lng',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_hours',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_image',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_logo',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_name',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_phone',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='struct_org_type',
        ),
    ]
