# Generated by Django 3.1.5 on 2021-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210128_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='breadcrumbs_are_active',
            field=models.BooleanField(default=True, help_text='If enabled, the breadcrumb object will be added as: https://example.org/{slug}/#breadcrumb . Also BreadCrumbList object will be added with the parent pages.', verbose_name='Breadcrumbs are active'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='breadcrumbs_are_active',
            field=models.BooleanField(default=True, help_text='If enabled, the breadcrumb object will be added as: https://example.org/{slug}/#breadcrumb . Also BreadCrumbList object will be added with the parent pages.', verbose_name='Breadcrumbs are active'),
        ),
    ]
