# Generated by Django 3.2.10 on 2021-12-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210731_1335'),
        ('home', '0006_auto_20210128_1346'),
    ]

    operations = [
    ]
