# Generated by Django 3.2.10 on 2021-12-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211227_1028'),
        ('home', '0007_merge_0002_auto_20210731_1335_0006_auto_20210128_1346'),
    ]

    operations = [
    ]
